#Pandas
1. python library
2. data manipulation and analysis
3. data structures

In [ ]:
import pandas as pd
#library un difeernt extensions plp

In [ ]:
df = pd.Series([11,22,33,44,55,66])
#s xapital or errror

In [ ]:
type(df)

pandas.core.series.Series

In [ ]:
print(df)

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64


In [ ]:
df[2]

33

In [ ]:
df[-2] #cannot access -ve index

KeyError: -2

In [ ]:
#auto iteration
for item in df:
  print(item)

11
22
33
44
55
66


In [ ]:
#index iteration
for index in range(len(df)):
  print("at",index,"We have:",df[index])

at 0 We have: 11
at 1 We have: 22
at 2 We have: 33
at 3 We have: 44
at 4 We have: 55
at 5 We have: 66


In [ ]:
#use of * is in scalar multiplication
l = [11,22,33]
print("List \n",l*2)
print("Series \n",df*2)

List 
 [11, 22, 33, 11, 22, 33]
Series 
 0     22
1     44
2     66
3     88
4    110
5    132
dtype: int64


In [ ]:
print("List\n",l/2)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
print("Series\n",df/2)

Series
 0     5.5
1    11.0
2    16.5
3    22.0
4    27.5
5    33.0
dtype: float64


In [ ]:
df

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64

In [ ]:
df = df/2
df

0     5.5
1    11.0
2    16.5
3    22.0
4    27.5
5    33.0
dtype: float64

In [ ]:
sum(df)

115.5

In [ ]:
min(df)

5.5

In [ ]:
max(df)

33.0

In [ ]:
len(df)

6

In [ ]:
#print numbers greater than avg of series
s = pd.Series([5,12,6,7,9,22,35,65,9,11,23,67,89])

In [ ]:
avg = sum(s)/len(s)

In [ ]:
print("Average is: ",avg)

Average is:  27.692307692307693


In [ ]:
for item in s:
  if item>=avg:
    print(item)

35
65
67
89


In [ ]:
from google.colab import files #method to upload an existing files
uploaded = files.upload()

Saving mydata.csv to mydata.csv


In [ ]:
import pandas as pd
import io
df = pd.read_csv(io.BytesIO(uploaded['mydata.csv'])) #method to read file BIO always capital

In [ ]:
df

,seatno,name,gender,pointer
0,1,aaaa,m,8.9
1,2,bbb,m,7.2
2,3,ccc,m,8.2
3,4,ddd,f,9.1
4,5,eee,f,8.5
5,6,fff,m,9.1
6,7,ggg,f,9.3
7,8,hhh,f,8.7
8,9,iii,m,3.4
9,10,jjj,m,2.1


In [ ]:
df.name #access one column at a time

0    aaaa
1     bbb
2     ccc
3     ddd
4     eee
5     fff
6     ggg
7     hhh
8     iii
9     jjj
Name: name, dtype: object

In [ ]:
df['name']

0    aaaa
1     bbb
2     ccc
3     ddd
4     eee
5     fff
6     ggg
7     hhh
8     iii
9     jjj
Name: name, dtype: object

In [ ]:
df

,seatno,name,gender,pointer
0,1,aaaa,m,8.9
1,2,bbb,m,7.2
2,3,ccc,m,8.2
3,4,ddd,f,9.1
4,5,eee,f,8.5
5,6,fff,m,9.1
6,7,ggg,f,9.3
7,8,hhh,f,8.7
8,9,iii,m,3.4
9,10,jjj,m,2.1


In [ ]:
print(df.name,df.gender)

0    aaaa
1     bbb
2     ccc
3     ddd
4     eee
5     fff
6     ggg
7     hhh
8     iii
9     jjj
Name: name, dtype: object 0    m
1    m
2    m
3    f
4    f
5    m
6    f
7    f
8    m
9    m
Name: gender, dtype: object


In [ ]:
df[['name','gender']]

,name,gender
0,aaaa,m
1,bbb,m
2,ccc,m
3,ddd,f
4,eee,f
5,fff,m
6,ggg,f
7,hhh,f
8,iii,m
9,jjj,m


In [ ]:
df[['name','pointer']]

,name,pointer
0,aaaa,8.9
1,bbb,7.2
2,ccc,8.2
3,ddd,9.1
4,eee,8.5
5,fff,9.1
6,ggg,9.3
7,hhh,8.7
8,iii,3.4
9,jjj,2.1


In [ ]:
df['percent'] = df['pointer']*10
print(df)

   seatno  name gender  pointer  percent
0       1  aaaa      m      8.9     89.0
1       2   bbb      m      7.2     72.0
2       3   ccc      m      8.2     82.0
3       4   ddd      f      9.1     91.0
4       5   eee      f      8.5     85.0
5       6   fff      m      9.1     91.0
6       7   ggg      f      9.3     93.0
7       8   hhh      f      8.7     87.0
8       9   iii      m      3.4     34.0
9      10   jjj      m      2.1     21.0


In [ ]:
df.to_csv("NewFile.csv")

In [ ]:
df1 = pd.read_csv('NewFile.csv')

In [ ]:
df1

,Unnamed: 0,seatno,name,gender,pointer,percent
0,0,1,aaaa,m,8.9,89.0
1,1,2,bbb,m,7.2,72.0
2,2,3,ccc,m,8.2,82.0
3,3,4,ddd,f,9.1,91.0
4,4,5,eee,f,8.5,85.0
5,5,6,fff,m,9.1,91.0
6,6,7,ggg,f,9.3,93.0
7,7,8,hhh,f,8.7,87.0
8,8,9,iii,m,3.4,34.0
9,9,10,jjj,m,2.1,21.0


In [ ]:
for item in df1: #way to know all columns in df1
  print(item)

Unnamed: 0
seatno
name
gender
pointer
percent


In [ ]:
#record printing
for index in range(len(df)):
  print(df.loc[index])

seatno        1
name       aaaa
gender        m
pointer     8.9
percent    89.0
Name: 0, dtype: object
seatno        2
name        bbb
gender        m
pointer     7.2
percent    72.0
Name: 1, dtype: object
seatno        3
name        ccc
gender        m
pointer     8.2
percent    82.0
Name: 2, dtype: object
seatno        4
name        ddd
gender        f
pointer     9.1
percent    91.0
Name: 3, dtype: object
seatno        5
name        eee
gender        f
pointer     8.5
percent    85.0
Name: 4, dtype: object
seatno        6
name        fff
gender        m
pointer     9.1
percent    91.0
Name: 5, dtype: object
seatno        7
name        ggg
gender        f
pointer     9.3
percent    93.0
Name: 6, dtype: object
seatno        8
name        hhh
gender        f
pointer     8.7
percent    87.0
Name: 7, dtype: object
seatno        9
name        iii
gender        m
pointer     3.4
percent    34.0
Name: 8, dtype: object
seatno       10
name        jjj
gender        m
pointer     2.1
percent  

In [ ]:
print(df.head(4)) #default first 5 records

   seatno  name gender  pointer  percent
0       1  aaaa      m      8.9     89.0
1       2   bbb      m      7.2     72.0
2       3   ccc      m      8.2     82.0
3       4   ddd      f      9.1     91.0


In [ ]:
print(df.tail(2)) #default last 5 records

   seatno name gender  pointer  percent
8       9  iii      m      3.4     34.0
9      10  jjj      m      2.1     21.0


In [ ]:
df_even = df.loc[0::2]

In [ ]:
df_even

,seatno,name,gender,pointer,percent
0,1,aaaa,m,8.9,89.0
2,3,ccc,m,8.2,82.0
4,5,eee,f,8.5,85.0
6,7,ggg,f,9.3,93.0
8,9,iii,m,3.4,34.0


In [ ]:
df_odd = df.loc[1::2]

In [ ]:
df_odd

,seatno,name,gender,pointer,percent
1,2,bbb,m,7.2,72.0
3,4,ddd,f,9.1,91.0
5,6,fff,m,9.1,91.0
7,8,hhh,f,8.7,87.0
9,10,jjj,m,2.1,21.0


In [ ]:
df.gender == "m"

0     True
1     True
2     True
3    False
4    False
5     True
6    False
7    False
8     True
9     True
Name: gender, dtype: bool

In [ ]:
df[(df['gender']=='f')]# toprint female gender

,seatno,name,gender,pointer,percent
3,4,ddd,f,9.1,91.0
4,5,eee,f,8.5,85.0
6,7,ggg,f,9.3,93.0
7,8,hhh,f,8.7,87.0


In [ ]:
df

,seatno,name,gender,pointer,percent
0,1,aaaa,m,8.9,89.0
1,2,bbb,m,7.2,72.0
2,3,ccc,m,8.2,82.0
3,4,ddd,f,9.1,91.0
4,5,eee,f,8.5,85.0
5,6,fff,m,9.1,91.0
6,7,ggg,f,9.3,93.0
7,8,hhh,f,8.7,87.0
8,9,iii,m,3.4,34.0
9,10,jjj,m,2.1,21.0


In [ ]:
df.sort_values(by="pointer")

,seatno,name,gender,pointer,percent
9,10,jjj,m,2.1,21.0
8,9,iii,m,3.4,34.0
1,2,bbb,m,7.2,72.0
2,3,ccc,m,8.2,82.0
4,5,eee,f,8.5,85.0
7,8,hhh,f,8.7,87.0
0,1,aaaa,m,8.9,89.0
3,4,ddd,f,9.1,91.0
5,6,fff,m,9.1,91.0
6,7,ggg,f,9.3,93.0


In [ ]:
#create a dataframe it is dict :key and values 2 dimensiioal data structures, can be created by uploading sql ,csv and excel
dfnew = pd.DataFrame({"Name":["Vijeta","Aniket","Piyush"],"Gender":["f","m","m"],"salary":[10,20,15],"empid":[1,2,3]})#df capital

In [ ]:
dfnew

,Name,Gender,salary,empid
0,Vijeta,f,10,1
1,Aniket,m,20,2
2,Piyush,m,15,3


In [ ]:
del dfnew['empid']

,seatno,name,gender,pointer,percent
0,1,aaaa,m,8.9,89.0
1,2,bbb,m,7.2,72.0
2,3,ccc,m,8.2,82.0
3,4,ddd,f,9.1,91.0
4,5,eee,f,8.5,85.0
5,6,fff,m,9.1,91.0
6,7,ggg,f,9.3,93.0
7,8,hhh,f,8.7,87.0
8,9,iii,m,3.4,34.0
9,10,jjj,m,2.1,21.0


In [ ]:
dfnew

,Name,Gender,salary
0,Vijeta,f,10
1,Aniket,m,20
2,Piyush,m,15


#Numpy

In [ ]:
import numpy as np
#it uses list for creating array

In [ ]:
n = np.array([11,22,33,66,77,88]) #1d

In [ ]:
n.shape

(6,)

In [ ]:
n.ndim #1d/2d/3d

1

In [ ]:
n.size

6

In [ ]:
m = np.array([[11,22,33],[66,77,88]]) #2d

In [ ]:
m.shape

(2, 3)

In [ ]:
m.ndim

2

In [ ]:
m.size

6

In [ ]:
a = np.arange(1,11,1)

In [ ]:
a #1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
a = np.arange(1,24,2).reshape(3,4)

In [ ]:
a

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
a = a+a

In [ ]:
a

array([[ 2,  6, 10, 14],
       [18, 22, 26, 30],
       [34, 38, 42, 46]])

In [ ]:
a[1][1]

22

In [ ]:
a[1:3,1:2]

array([[22],
       [38]])

In [ ]:
from numpy import random

In [ ]:
n = random.randint(12)
#any number from 0 to given n
print(n)

10


In [ ]:
n = random.randint(100,size=(6,6))

In [ ]:
print(n)

[[79 62 90 17 35 59]
 [90 87 26 26 52  6]
 [99 99 82  3 27 50]
 [46 18 63 67 25 80]
 [40 52  6 45 52 33]
 [ 6 25 97 29 70 63]]


In [ ]:
n = random.choice(["Ajay","sanchita","Sayali","Farhat","Avdhut"])
print(n)

Avdhut


In [ ]:
m = random.rand(7)

In [ ]:
m

array([0.38809929, 0.81348937, 0.79652122, 0.90699152, 0.96517683,
       0.94294172, 0.01695788])